services:
  web:
    build: ./
    env_file:
      - .env
    ports:
      - "8000:80"
    depends_on: 
      - db
  
  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
